env:
  es2021: true
  node: true
plugins:
  - 'prettier'
extends:
  - airbnb-base
  - 'plugin:prettier/recommended'
  - 'prettier'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  { 'no-console': 0, import/extensions: 0, no-await-in-loop: 0, no-plusplus: 0 }
